# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 12:17
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'bloodbank',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.Country')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.Country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bloodgroup', models.CharField(choices=[('ap', 'A+ve'), ('an', 'A-ve'), ('abn', 'AB-ve'), ('abp', 'AB+ve'), ('op', 'o+ve'), ('on', 'o-ve'), ('bp', 'B+ve'), ('bn', 'B-ve')], max_length=3)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.State')),
            ],
            options={
                'db_table': 'userprofile',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.State'),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.Organization'),
        ),
    ]
