# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ap', 'A+ve'), ('an', 'A-ve'), ('abn', 'AB-ve'), ('abp', 'AB+ve'), ('op', 'o+ve'), ('on', 'o-ve'), ('bp', 'B+ve'), ('bn', 'B-ve')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bloodgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.BloodGroup'),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='bloodgroups',
            field=models.ManyToManyField(to='bloodgroup.BloodGroup'),
        ),
    ]
