# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodgroup', '0002_auto_20180804_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
