# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodgroup', '0002_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodgroup.UserProfile'),
        ),
    ]
