# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodgroup', '0005_auto_20180811_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='donar', max_length=25),
        ),
    ]
